### ISSUE TITLE
Badge not hidden

### ISSUE THREAD

**Issue by jeremy-jamez** [rahimlis/badgedtablayout#1]
I've tried `tabs.setBadgeText(0, null)` and the badge still displays.
This is my TabLayout implementation:
 `tabs = (BadgedTabLayout) v.findViewById(R.id.result_tabs);
        tabs.setupWithViewPager(viewPager);`

ViewPager setup:
`private void setupViewPager(final ViewPager viewPager) {
        final Adapter adapter = new Adapter(getChildFragmentManager());

        ValueEventListener valueEventListener = new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                Users users = dataSnapshot.getValue(Users.class);

                adapter.addFragment(new NotificationFragment(), "Notifications");
                adapter.addFragment(new AccountFragment(), users.getUsername());

                tabs.setBadgeText(0, null);
                tabs.setBadgeText(1, null);

                viewPager.setAdapter(adapter);

                adapter.notifyDataSetChanged();

                viewPager.setCurrentItem(adapter.getCount() - 1);
            }

            @Override
            public void onCancelled(DatabaseError databaseError) {
                Log.w("AccountFragment", "loadPost:onCancelled", databaseError.toException());
            }
        };
        mDatabaseRef.addValueEventListener(valueEventListener);
    }`

**Comment by rahimlis** [comment]
i will check that :+1:  thank you for noticing

**Comment by rahimlis** [comment]
please check your logs, for the message "Tab is null". If there is such message it means your tab is not correctly initialized. You can check updated example everything works there

**Comment by rahimlis** [comment]
it seems like you messed up your code :)  try to set adapter first, then use `setBadgeText`
