### ISSUE TITLE
Tab Text Size

### ISSUE THREAD

**Issue by nburaktaban** [rahimlis/badgedtablayout#5]
Hi, There is no method for 'tabTextSize'. Text size is big for my app. How do I decrease it?

**Comment by rahimlis** [comment]
Look at this answer, setting it in normal way should do the trick
https://stackoverflow.com/questions/31471177/text-size-of-android-design-tablayout-tabs#answer-31833065

**Comment by nburaktaban** [comment]
It did not work. Any other suggestions?

**Comment by rahimlis** [comment]
please use it as in example 
`<com.rahimlis.badgedtablayout.BadgedTabLayout
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:badgeBackgroundColor="@color/badge_background_color"
            app:badgeTextSize="11sp"
            app:tabIndicatorColor="#4f4" />`

badgeTextSize will do the trick

**Comment by rahimlis** [comment]
added setters for tab text size
