### ISSUE TITLE
Question: How to add text without animation

### ISSUE THREAD

**Issue by rbatllet** [rahimlis/badgedtablayout#8]
I want something like Whatsapp. But currently, the text in the tab is moving from right to left. How to stop moving it disabling the marquee?

![screen shot 2018-01-18 at 16 16 44](https://user-images.githubusercontent.com/3993987/35105223-5b7df724-fc6b-11e7-84f7-14f523e0efca.png)

**Comment by rahimlis** [comment]
i will consider this in next update

**Comment by rahimlis** [comment]
added in new version
